export const STUDENT_LOGIN = 'STUDENT_LOGIN';
export const ADMIN_LOGIN = 'ADMIN_LOGIN';
export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';

export const CLEAR_AUTHENTICATION = 'CLEAR_AUTHENTICATION';

export const BEGIN_REGISTER_STUDENT = 'BEGIN_REGISTER_STUDENT';
export const REGISTER_STUDENT = 'REGISTER_STUDENT';
export const END_REGISTER_STUDENT = 'END_REGISTER_STUDENT';
export const ERROR_REGISTER_STUDENT = 'ERROR_REGISTER_STUDENT';

export const START_DOCUMENT_LIST_FETCH = 'START_DOCUMENT_LIST_FETCH';
export const SUCCESS_DOCUMENT_LIST_FETCH = 'SUCCESS_DOCUMENT_LIST_FETCH';
export const ERROR_DOCUMENT_LIST_FETCH = 'ERROR_DOCUMENT_LIST_FETCH';

export const CLEAR_REQUEST_FORM_DATA = 'CLEAR_REQUEST_FORM_DATA';

export const START_REQUEST_FORM_SUBMIT = 'START_REQUEST_FORM_SUBMIT';
export const SUCCESS_REQUEST_FORM_SUBMIT = 'SUCCESS_REQUEST_FORM_SUBMIT';
export const ERROR_REQUEST_FORM_SUBMIT = 'ERROR_REQUEST_FORM_SUBMIT';

export const START_STUD_REQ_LISTING_FETCH = 'START_STUD_REQ_LISTING_FETCH';
export const SUCCESS_STUD_REQ_LISTING_FETCH = 'SUCCESS_STUD_REQ_LISTING_FETCH';
export const ERROR_STUD_REQ_LISTING_FETCH = 'ERROR_STUD_REQ_LISTING_FETCH';

export const START_STUD_REQ_DELETE = 'START_STUD_REQ_DELETE';
export const SUCCESS_STUD_REQ_DELETE = 'SUCCESS_STUD_REQ_DELETE';
export const ERROR_STUD_REQ_DELETE = 'ERROR_STUD_REQ_DELETE';

export const START_DOC_CREATE = 'START_DOC_CREATE';
export const SUCCESS_DOC_CREATE = 'SUCCESS_DOC_CREATE';
export const ERROR_DOC_CREATE = 'ERROR_DOC_CREATE';

export const ADMIN_API_CALL_START = 'ADMIN_API_CALL_START';
export const ADMIN_API_CALL_END = 'ADMIN_API_CALL_END';
export const ADMIN_API_CALL_ERROR = 'ADMIN_API_CALL_ERROR';
export const ADMIN_API_CALL_UPDATE_DOCUMENT = 'ADMIN_API_CALL_UPDATE_DOCUMENT';
export const ADMIN_API_CALL_DELETE_DOCUMENT = 'ADMIN_API_CALL_DELETE_DOCUMENT';
export const ADMIN_API_CALL_CREATE_ACCOUNT = 'ADMIN_API_CALL_CREATE_ACCOUNT';
